### PR TITLE
Function

### PR DESCRIPTION
**Pull request by hadttfpt**
Chuc nang tim kiem thong tin user tren git

### CODE REVIEW

**Comment by hadttfpt** [comment]
Screenshot_20211009-165151

**Comment by hadttfpt** [comment]
Screenshot_20211009-164453

**Comment by hadttfpt** [comment]
Screenshot_20211009-164530

**Comment by ducvu212** [comment]
fix conflict

**Comment by hadttfpt** [comment]
da r anh aj

**Pull request merged**
